appgotogym/urls.py
from django.urls.conf import include
from django.contrib import admin
from django.urls import path

##importamos para el proceso de las imagenes
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include(('applogin.urls','applogin'), namespace='applogin')),   #ruta para el fichero URLS dentro del directorio APPLIGUIN
    path('admin/', admin.site.urls),    #ruta para ingresar al panel de control
    path('social-auth/', include('social_django.urls', namespace="social")), ##autenticacion con facebook
]

##Esta linea de DEBUD solo sirve en desarrollo
##Cuando esta en produccion podria crear un ENGINE
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

applogin/urls.py
from applogin import views  ##para poder llamar a las funciones creadas en Views.py
from django.urls import path
from django.contrib.auth import views as vistas_sesion  ##Vistas para el login
from applogin.views import *
from django.urls import re_path
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.urls import reverse_lazy
from .views import MostrarUser, RegistroUser

app_name = "config"

urlpatterns = [
    path('l/', Home.as_view(), name='home'),
    path('', RedirectView.as_view(url='home', permanent=False), name='r_home'),  ##hace una redireccion hacia otra pagina
    path('login/', vistas_sesion.LoginView.as_view(template_name='apploginp/login.html'), name='login'),
    path('logout/', vistas_sesion.LogoutView.as_view(template_name='apploginp/home.html'), name='logout'),
    path('home/', vistas_sesion.LoginView.as_view(template_name='apploginp/home2.html'), name='home'),
    #path('home/gotogym', QuienesSomos.as_view(), name='home_quienessomos'),
    path('home/gotogym', vistas_sesion.LoginView.as_view(template_name='apploginp/home_quienesSomos.html'), name='home_quienessomos'),  ##De esta manera se puede iniciar sesion desde este template sin crear una Views
    path('home/preguntas_frecuentes', vistas_sesion.LoginView.as_view(template_name='apploginp/home_preguntasFrecuentes.html'), name='home_preguntasfrecuentes'),   ##De esta manera se puede iniciar sesion desde este template sin crear una Views
    path('home/devoluciones', vistas_sesion.LoginView.as_view(template_name='apploginp/home_devoluciones.html'), name='home_devoluciones'), ##De esta manera se puede iniciar sesion desde este template sin crear una Views
    path('home/cultura_corporativa', vistas_sesion.LoginView.as_view(template_name='apploginp/home_culturaCorporativa.html'), name='home_culturacorporativa'),  ##De esta manera se puede iniciar sesion desde este template sin crear una Views
    path('home/politicas_privacidad', vistas_sesion.LoginView.as_view(template_name='apploginp/home_politicayprivacidad.html'), name='home_politicayprivacidad'),   ##De esta manera se puede iniciar sesion desde este template sin crear una Views
    #path('home/contactanos', vistas_sesion.LoginView.as_view(template_name='apploginp/home_contactanos.html'), name='home_contactanos'),   ##De esta manera se puede iniciar sesion desde este template sin crear una Views
    #path('home/relaciones_inversionistas', vistas_sesion.LoginView.as_view(template_name='apploginp/home_relacionesConInversionistas.html'), name='home_relacionesconinversionistas'),   ##De esta manera se puede iniciar sesion desde este template sin crear una Views
    #path('home/trabaja_con_nosotros', vistas_sesion.LoginView.as_view(template_name='apploginp/home_trabajaConNosotros.html'), name='home_trabajaconnosotros'),   ##De esta manera se puede iniciar sesion desde este template sin crear una Views
    #path('home/sesion', HomeLogout.as_view(template_name='apploginp/home_logout.html'), name='home_sesion'),
    path('home/contactanos/', views.contactomail, name='home_contactanos'),
    path('home/trabaja_con_nosotros/', views.trabajaconnosotros, name='home_trabajaconnosotros'),
    path('home/relaciones_inversionistas/', views.relacioninversionistas, name='home_relacionesconinversionistas'),
    path('user/', MostrarUser.as_view(), name='list_user'),
    path('user/registro', RegistroUser.as_view(), name='registro_user'),
    
    url(
        r'^user/recovery/$', auth_views.PasswordResetView.as_view(
            template_name='apploginp/reset_pass_form.html',
            html_email_template_name='apploginp/reset_pass_email.html',),
            name='password_reset',
    ),

    url(
        r'^user/recovery/cambiar/$',
        auth_views.PasswordResetDoneView.as_view(
            template_name='apploginp/reset_pass_cambiar.html',
        ),
        name='password_reset_done',
    ),

    url(
        r'^user/recovery/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('home'),
            post_reset_login=True,
            template_name='apploginp/reset_pass_confirmar.html',
            post_reset_login_backend=(
                'django.contrib.auth.backends.AllowAllUsersModelBackend'
            ),
        ),
        name='password_reset_confirm',
    ),


]

applogin/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.utils import timezone
from django.utils.http import urlquote
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, User

from appgotogym.settings import AUTH_USER_MODEL

from .managers import UsuarioManager


##Al heredar de AbstractBaseUser define automaticamente un campo contraseña
##PermissionsMixin permite generar los permisos de usuarios.
class Usuario(AbstractBaseUser,PermissionsMixin):
    dni = models.IntegerField(_('cedula'), null=True, blank=True)
    email = models.EmailField(_('direccion email'), max_length=254, unique=True)
    first_name = models.CharField(_('nombres'), max_length=30, blank=True)
    last_name = models.CharField(_('apellidos'), max_length=30, blank=True)
    date_birth = models.DateField(_('fecha nacimiento'), null=True)
    num_telf = models.CharField(_('numero telefono'), max_length=20, blank=True)
    num_cell = models.CharField(_('numero celular'), max_length=20, blank=True)
    is_staff = models.BooleanField(_('es staff'), default=False,
        help_text=_('Indica si el usuario puede iniciar sesión en admin.'))
    is_active = models.BooleanField(_('activo'), default=True,  ###########################
        help_text=_('Designa si este usuario debe ser tratado como activo'
                    'Deseleccione esto en lugar de eliminar cuentas.'))
    user_crea = models.EmailField(_('usuario crea'), blank=True,null=True,  #########################
        help_text=_('Indica que usuario creo a cual usuario'))  
    user_mod = models.EmailField(_('usuario modifica'), blank=True,null=True,   ##################################
         help_text=_('Indica que usuario modifico a cual usuario'))
    date_joined = models.DateTimeField(_('fecha registro'), default=timezone.now)
    dni_tipo = models.CharField(_('tipo documento'), max_length=15, blank=True)
    pais = models.CharField(_('pais'), max_length=20, blank=True)
    ciudad = models.CharField(_('ciudad'), max_length=25, blank=True)
    direccion = models.CharField(_('direccion'), max_length=60, blank=True)
    cod_postal = models.CharField(_('codigo postal'), max_length=10, blank=True)
    imagen = models.ImageField(_('imagen usuario'), upload_to='imagen_user', null=True)
    

    USERNAME_FIELD = 'email' ##Le decimos que el usuario sera el correo electronico
    REQUIRED_FIELDS = []    #especifica los demas campos requeridos.

    objects = UsuarioManager()  #Le indicamos que utilice la configuracion del fichero managers.py

    class Meta:
        verbose_name = _('usuario') #para traducir el nombre de los campos creados
        verbose_name_plural = _('usuarios')

    def get_absolute_url(self):
        return "/users/%s" % urlquote(self.email)   #se sobrescribe para que el usuario sea el correo
    
    def get_full_name(self):
        full_name = "%s %s" % (self.first_name,self.last_name) ##retorna el nombre y apellido
        return full_name.strip()
    
    def get_short_name(self):
        return self.first_name


##Clase con campos que se repiten en cada tabla.
##Los modelos que se creen, heredaran estos campos.
class ClaseModelo(models.Model):
    estado = models.BooleanField(_('estado'),default=True)  #todos los objetos se crearan con un estado activo.
    date_crea = models.DateTimeField(_('fecha de creación'),auto_now_add=True)    #registrar la fecha de creacion.
    date_mod = models.DateTimeField(_('fecha de modificación'),auto_now=True)    #registra la fecha de la modificacion.
    user_crea = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)  #registra al usuario que crea y toma el id.
    user_mod = models.IntegerField(_('Usuario que modifica'),blank=True,null=True)

    class Meta:
        abstract = True #Para indicarque que este modelo no sea tomado en cuenta en la migracion

applogin/forms.py
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.db import models
from django.forms import fields
from django import forms

from .models import Usuario

class UsuarioCreationForm(UserCreationForm):
    
    class Meta:
        model = Usuario
        fields = ("first_name","last_name","date_birth","num_telf","email",)
    
    def __init__(self,*args,**kwargs):
        super(UsuarioCreationForm,self).__init__(*args,**kwargs)


class UsuarioChangeForm(UserChangeForm):
    def __init__(self,*args,**kwargs):
        super(UsuarioChangeForm,self).__init__(*args,**kwargs)

    class Meta:
        model = Usuario
        fields = '__all__'


"""class UsuarioCreationForm(UserCreationForm):
    def __init__(self,*args,**kwargs):
        super(UsuarioCreationForm,self).__init__(*args,**kwargs)

    class Meta:
        model = Usuario
        fields = ("email",)


class UsuarioChangeForm(UserChangeForm):
    def __init__(self,*args,**kwargs):
        super(UsuarioChangeForm,self).__init__(*args,**kwargs)

    class Meta:
        model = Usuario
        fields = '__all__' """


"""class UsuarioForm(forms.ModelForm):
    class Meta: ##especificamos los datos a tomar
        model = Usuario
        fields = ['email','password']
        labels = {'email':"Correo electronico",
        'password':"Contraseña"}
        widget= {'email':forms.TextInput}   #indicamos el tipo de elemento HTML a utilizar

    def __init__(self, *args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })"""

applogin/views.py
from django.shortcuts import render
from django.views.generic import *
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.urls import reverse_lazy

from django.core.mail import EmailMessage, send_mail, EmailMultiAlternatives
from django.conf import settings

import smtplib, ssl
import email
from email import encoders
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
import os

from django.views import generic
from .models import Usuario
from .forms import UsuarioCreationForm #, UsuarioForm

##Utilisando los Mixin se puede indicar que si un usuario no ha iniciado sesion
##Lo redirija por ejemplo a la  ventana de logeo o a la que indiquemos.
#class Home(LoginRequiredMixin, TemplateView):
    #template_name = 'apploginp/home.html'
    #login_url = 'config:login'

class Home(generic.TemplateView):
    template_name = 'apploginp/home.html'


#Para enviar un correo en "Contatenos"
def contactomail(request):
        if request.method == 'POST':
            asunto = 'Contacto GoToGym'
            if request.POST["agendar"] == '1':
                agendar_r = "Solicita agendar una reunión."
                message=request.POST["mensaje"] + ".\n\n" + "Correo del remitente: " + request.POST["email"] + "\n" + agendar_r
            else:
                message=request.POST["mensaje"] + ".\n\n" + "Correo del remitente: " + request.POST["email"]
            
            email_from = settings.EMAIL_HOST_USER   #correo de donde saldran los mensajes
            recipient_list = ["leopa_1512@hotmail.com"] #correo donde llegaran los mensajes

            if (len(message) > 0):
                send_mail(asunto, message, email_from, recipient_list)
                message = ""

        return render(request, "apploginp/home_contactanos.html")



#Para enviar correo en "Trabaja con Nosotros"
##Y enviar un documento adjunto al correo
def trabajaconnosotros(request):
    if request.method == 'POST':
        servidor = 'smtp.gmail.com'
        puerto = 465
        remitente = 'leo.parrales1512@gmail.com'  #correo de donde saldran los mensajes
        clave = 'xgnlhliiipghwelf'
        receptor = 'leopa_1512@hotmail.com'
        contexto = ssl.create_default_context()
        asunto = 'Trabaja con Nosotros'
        correo_r = "Correo del Contacto: " + request.POST["email"]
        nombre = "Nombre: " + request.POST["nombre"]
        apellido = "Apellido: " + request.POST["apellido"]
        dni = "Identificación: " + request.POST["dni"]
        pais = "País: " + request.POST["pais"]
        ciudad = "Ciudad: " + request.POST["ciudad"]
        direccion = "Dirección: " + request.POST["direccion"]
        telefono = "Num. Telefono: " + request.POST["telefono"]
        cuerpo = correo_r +".\n"+ nombre +".\n"+ apellido +".\n"+ dni +".\n"+ pais +".\n"+ ciudad +".\n"+ direccion +".\n"+ telefono

        message = MIMEMultipart()
        message['Subject'] = asunto
        message['From'] = remitente
        message['To'] = receptor

        message.attach(MIMEText(cuerpo, 'plain'))
        archivo = request.POST["curriculum"]
        #archivo = 'C:\\Users\\Pc\\Downloads\\grupo.pdf'

        #abrimos el documento en modo binario
        with open('C:\\Users\\Pc\\Downloads\\' + archivo, 'rb') as adjunto:
            pdf = MIMEBase('application','octet-stream')
            pdf.set_payload(adjunto.read())

        #lo codificamos en ascii para poder enviarlo
        encoders.encode_base64(pdf)
        pdf.add_header('Content-Disposition', f'attachment; filename={archivo}',)

        message.attach(pdf)
        texto = message.as_string()

        with smtplib.SMTP_SSL(servidor,puerto, context=contexto) as s:
            s.login(remitente, clave)
            s.sendmail(remitente, receptor, texto)

    return render(request, "apploginp/home_trabajaConNosotros.html")


##Para enviar formulario por correo
def relacioninversionistas(request):
        if request.method == 'POST':
            asunto = 'Relaciones con Inversionistas'
            correo_r = "Correo del Contacto: " + request.POST["email"]
            nombre = "Nombre: " + request.POST["nombre"]
            apellido = "Apellido: " + request.POST["apellido"]
            trabajo = "Tipo de trabajo: " + request.POST["trabajo"]
            compania = "Compañia: " + request.POST["compania"]
            linkedin = "Linkedin: " + request.POST["linkedin"]
            mensaje = "Mensaje: \n" + request.POST["mensaje"]

            message= correo_r +".\n"+ nombre +".\n"+ apellido +".\n"+ trabajo +".\n"+ compania +".\n"+ linkedin +".\n\n"+ mensaje
            email_from = settings.EMAIL_HOST_USER   #correo de donde saldran los mensajes
            recipient_list = ["leopa_1512@hotmail.com"] #correo donde llegaran los mensajes

            if (len(message) > 0):
                send_mail(asunto, message, email_from, recipient_list)
                message = ""

        return render(request, "apploginp/home_relacionesConInversionistas.html")


##Mostrar Listado de usuarios registrados
class MostrarUser(LoginRequiredMixin, generic.ListView):
    model = Usuario
    template_name = 'apploginp/list_user.html'
    context_object_name = 'obj' #cambio el nombre al objeto
    login_url = 'applogin:login'   #Si no esta logeado lo redirige 


#define la ruta del formulario de registro del usuario
#luego de registrado se redirige a otra pagina
class RegistroUser(generic.CreateView):
    model = Usuario
    template_name = 'apploginp/registro_user.html'
    context_object_name = 'obj' #cambio el nombre al objeto
    form_class = UsuarioCreationForm
    success_url = reverse_lazy('applogin:list_user')   #hace una redireccion

    def form_valid(self, form):
        form.instance.user_crea = self.request.user #para optener el usuario que crea
        return super().form_valid(form)


"""class RegistroUser(LoginRequiredMixin, generic.CreateView):
    model = Usuario
    template_name = 'apploginp/registro_user.html'
    context_object_name = 'obj' #cambio el nombre al objeto
    form_class = UsuarioForm
    success_url = reverse_lazy('applogin:list_user')   #hace una redireccion
    login_url = 'applogin:login'   #Si no esta logeado lo redirige 

    def form_valid(self, form):
        form.instance.user_crea = self.request.user #para optener el usuario que crea
        return super().form_valid(form)"""

applogin/templates/apploginp/home2.html
{% extends "applogin/index.html" %}

{% block js_page %}
{% endblock js_page %}

applogin/templates/apploginp/home_logout.html
{% extends "applogin/index.html" %}

{% block cabecera_inicio %}
        <!-- home Navbar-->
        <ul class="nav justify-content-end">
            <li class="nav-item">
                <a class="nav-link text-muted" href="#!">{{ user.first_name | title }} {{ user.last_name | title }} Bienvenido.</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-muted" href="#!">Ayuda</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-info" href="{% url 'applogin:logout' %}">Cerrar Sesión</a>
            </li>
        </ul>
        <!--/. home Navbar-->
{% endblock cabecera_inicio %}

applogin/templates/apploginp/home_trabajaConNosotros.html
{% extends "applogin/index.html" %}

{% block contenido %}
<!-- Start your project here -->
<div class="container my-5">
    <div class="row">
        <div class="col-md-6 text-justify mb-5">
            <h4>Trabaja con nosotros</h4>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque minima asperiores et perspiciatis molestiae. Quo aspernatur accusantium voluptas sed cumque repellendus error aut quod repellat officiis ab, laborum nemo debitis?</p>
            <img src="https://img.freepik.com/vector-gratis/caracter-oficina-trabajo-equipo-personas-negocios-discute-colega-dispositivos_40876-1353.jpg?size=626&ext=jpg"
                class="img-fluid z-depth-1" alt="hoverable">
        </div>
        <div class="col-md-6 px-5">
            <form action="" method="post" id="id_tnosotros">
                {% csrf_token %}

                <h4>Información de contacto</h4>

                <div class="md-form">
                    <input type="email" name="email" id="id_email" class="form-control" required>
                    <label for="form1">E-mail</label>
                </div>

                <h4>Información Personal</h4>
                <div class="row">

                    <div class="col-md-6">
                        <div class="md-form">
                            <input type="text" name="nombre" id="id_nombre" class="form-control" required>
                            <label for="form1">Nombre</label>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="md-form">
                            <input type="text" name="apellido" id="id_apellido" class="form-control" required>
                            <label for="form1">Apellidos</label>
                        </div>
                    </div>

                    <div class="col-md-12">
                        <div class="md-form">
                            <input type="number" name="dni" id="id_dni" class="form-control">
                            <label for="form1">Cédula / RUC</label>
                        </div>
                    </div>

                    <div class="col-md-6 mb-4">
                        <select name="pais" id="id_pais" class="browser-default custom-select" required>
                            <option selected>País</option>
                            <option value="Ecuador">Ecuador</option>
                            <option value="Colombia">Colombia</option>
                            <option value="Peru">Perú</option>
                        </select>
                    </div>
                    <div class="col-md-6">
                        <select name="ciudad" id="id_ciudad" class="browser-default custom-select" required>
                            <option selected>Ciudad</option>
                            <option value="Cali">Cali</option>
                            <option value="Bogota">Bogotá</option>
                            <option value="Medellin">Medellin</option>
                        </select>
                    </div>

                    <div class="col-md-12">
                        <div class="custom-file">
                            <input type="file" name="curriculum" id="id_curriculum" class="custom-file-input" enctype="multipart/form-data">
                            <label class="custom-file-label" for="customFileLang" data-browse="Subir Archivo">Currículum Vitae (archivo en .pdf)</label>
                        </div>
                    </div>

                    <div class="col-md-12">
                        <div class="md-form">
                            <input type="text" name="direccion" id="id_direccion" class="form-control">
                            <label for="form1">Dirección</label>
                        </div>
                    </div>

                    <div class="col-md-12">
                        <div class="md-form">
                            <input type="tel" name="telefono" id="id_telefono" class="form-control" required>
                            <label for="form1">Teléfono / Celular</label>
                        </div>
                    </div>
                    <div class="col-md-12 text-center">
                        <button class="btn btn-mdb-color" data-toggle="modal" data-target="#">Enviar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- End your project here-->

<!-- Central Modal Medium Success -->
<div class="modal fade" id="centralModalSuccess" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
aria-hidden="true">
<div class="modal-dialog modal-notify modal-success" role="document">
  <!--Content-->
  <div class="modal-content">
    <!--Header-->
    <div class="modal-header">
      <p class="heading lead">Felicidades</p>

      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true" class="white-text">&times;</span>
      </button>
    </div>

    <!--Body-->
    <div class="modal-body">
      <div class="text-center">
        <i class="fas fa-check fa-4x mb-3 animated rotateIn"></i>
        <p>Su solicitud ha sido enviada con éxito, nos contactaremos con usted a la brevedad posible</p>
      </div>
    </div>

    <!--Footer-->
    <div class="modal-footer justify-content-center">
      <a type="button" class="btn btn-outline-success waves-effect" data-dismiss="modal">Aceptar</a>
    </div>
  </div>
  <!--/.Content-->
</div>
</div>
<!-- Central Modal Medium Success-->
{% endblock contenido %}

{% block pie_pagina %}
{% endblock pie_pagina %}

applogin/templates/apploginp/registro_user1.html
{% extends "applogin/index.html" %}

{% block cabecera_inicio %}
<!-- home Navbar-->
<ul class="nav justify-content-end">
    <li class="nav-item">
        <a class="nav-link text-muted" href="#!">{{ user.first_name | title }} {{ user.last_name | title }} Bienvenido.</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-muted" href="#!">Ayuda</a>
        <a class="nav-link text-muted" data-toggle="modal" data-target="#modalRegisterForm" href="#!">Registrarse</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-info" href="{% url 'applogin:logout' %}">Cerrar Sesión</a>
    </li>
</ul>
<!--/. home Navbar-->
{% endblock cabecera_inicio %}

{% block contenido %}
<form method="POST" class="form-inline">
    {% csrf_token %}    <!--este es el token de seguridad, siempre colocarlo cuando usamos POST-->
    <div class="col-xl-6 col-md-6 mb-6">
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
        {% else %}
        <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                            {% if obj %} Editar {% else %} Nueva {% endif %} Categoría
                        </div>
                        <!--desde aquí creamos el formulario-->
                        <div class="dropdownn-divider"></div>
                        <div class="row">
                            <div class="col-10">
                                <div class="input-group">
                                    <input type="text" name="email" maxlength="100" class="form-control" required id="id_email" placeholder="Correo" 
                                    value="{% if obj %} {{obj.username}} {% endif %}">
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="form-group">
                                    <label for="id_is_active">Estado</label>
                                    <input type="checkbox" name="is_active" class="form-control" id="id_is_active" {% if obj.is_active %} checked {% endif %}>
                                </div>
                            </div>
                            <!--de esta manera tambien se puede crear el formulario-->
                            <!-- {{ form.as_p }} -->
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Guardar</button>
                                
                            </div>
                        </div>
                    </div> 
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock contenido %}

{% block registro %}
<!-- ventana modal de registro -->
<form method="POST" id="registro" class="form-inline" action="">
    {% csrf_token %}
    <div class="col-xl-6 col-md-6 mb-6">
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
        {% else %}
        <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                            {% if obj %} Editar {% else %} Nueva {% endif %} Categoría
                        </div>
                        <!--desde aquí creamos el formulario-->
                        
                            <!--de esta manera tambien se puede crear el formulario-->
                            {{ form.as_p }}
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" onclick="registro(); return false;" class="btn btn-danger"><span class="fa fa-save"></span>Guardar</button>
                            </div>
                        </div>
                    </div> 
                </div>
            </div>
        </div>
    </div>
</form>
<!-- Fin ventana modal de registro -->
{% endblock registro %}

{% block js_page %}
<script>
    function registro(){
      document.getElementById('registro').submit();
      alert("Formulario enviado desde Java Script");
    }
</script>
{% endblock js_page %}

applogin/templates/apploginp/reset_pass_cambiar.html
{% extends "applogin/index.html" %}

{% block cabecera_inicio %}
{% endblock cabecera_inicio %}

{% block contenido %}
<section class="PasswordResetDone">
    <h3>Recuperación de contraseña.</h3>
    <p>Hemos enviado un correo electrónico con las instrucciones para recuperar su contrsaseña</p>
    <a href="{% url 'applogin:home' %}" class="btn btn-info">Home</a>
</section>
{% endblock contenido %}

{% block registro %}
{% endblock registro %}

{% block js_page %}
{% endblock js_page %}

applogin/templates/apploginp/reset_pass_email.html
    <h1 style="font-size: 1.5em; line-height: 2em;">Cordial saludo {{ user.first_name }}</h1>
    <p>Enviamos este mensaje para restablecer su contraseña. Haga clic en el siguiente enlace:</p>
    <p><a href="http://{{ domain }}{% url 'applogin:password_reset_confirm' uidb64=uid token=token %}">http://{{ domain }}{% url 'applogin:password_reset_confirm' uidb64=uid token=token %}</a></p>
    <p>Su correo electrónico registrado es:<b>{{ user.email }}</b></p>